<?php

namespace ContainerNtDGq14;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Value_B5LQtRpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.value.B5LQtRp' shared service.
     *
     * @return \mixed
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.value.B5LQtRp'] = \current([0 => (\dirname(__DIR__, 4).'/public/img2/profiler')]);
    }
}
