<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMxGaXdP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMxGaXdP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMxGaXdP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMxGaXdP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMxGaXdP\App_KernelDevDebugContainer([
    'container.build_hash' => 'MxGaXdP',
    'container.build_id' => '61b0c54c',
    'container.build_time' => 1645096554,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMxGaXdP');
