<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYk0uEb1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYk0uEb1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYk0uEb1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYk0uEb1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYk0uEb1\App_KernelDevDebugContainer([
    'container.build_hash' => 'Yk0uEb1',
    'container.build_id' => '95605c2e',
    'container.build_time' => 1645003589,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYk0uEb1');
