<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFBt8kmk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFBt8kmk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFBt8kmk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFBt8kmk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFBt8kmk\App_KernelDevDebugContainer([
    'container.build_hash' => 'FBt8kmk',
    'container.build_id' => '03a0d311',
    'container.build_time' => 1645008138,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFBt8kmk');
