<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'admin' => [[], ['_controller' => 'App\\Controller\\Admin\\DashboardController::index'], [], [['text', '/admin']], [], [], []],
    'precioCanal_show' => [['author'], ['_controller' => 'App\\Controller\\CanalController::findPrecioByAuthor'], [], [['variable', '/', '[^/]++', 'author', true], ['text', '/canal/precio']], [], [], []],
    'CanalAll_show' => [[], ['_controller' => 'App\\Controller\\CanalController::findCanalByAll'], [], [['text', '/canal/findAll']], [], [], []],
    'CanalAuthor_show' => [['author'], ['_controller' => 'App\\Controller\\CanalController::findCanalByAuthor'], [], [['variable', '/', '[^/]++', 'author', true], ['text', '/canal/find']], [], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], [], []],
    'app_verify_email' => [[], ['_controller' => 'App\\Controller\\RegistrationController::verifyUserEmail'], [], [['text', '/verify/email']], [], [], []],
    'editUser' => [['id'], ['_controller' => 'App\\Controller\\RegistrationController::editUset'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/user/edit']], [], [], []],
    'index' => [[], ['_controller' => 'App\\Controller\\RootController::index'], [], [['text', '/']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], [], []],
];
